# Generated by Django 2.0.5 on 2018-09-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nflp', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('seatcap', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
